# Generated by Django 5.0.2 on 2024-03-06 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 15, 54, 58, 521802)),
        ),
    ]
