# Generated by Django 5.0.2 on 2024-03-06 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='parmanent_address',
            new_name='permanent_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 17, 23, 33, 124043)),
        ),
    ]
