# Generated by Django 5.0.2 on 2024-03-07 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_parmanent_address_profile_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 9, 12, 49, 732122)),
        ),
    ]
