# Generated by Django 5.0.2 on 2024-03-07 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile_old_card_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 10, 52, 37, 442855)),
        ),
    ]
